Vagrant.configure("2") do |config|

    config.vm.define "control" do |control|
        control.vm.box = "ubuntu/bionic64"
        control.vm.network "private_network", ip: "192.168.10.12"
        control.vm.hostname = "control"
        control.vm.synced_folder "C:/Users/charm/Downloads/kubernetes_repo", "/vagrant_data"
        control.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.name = "control"
        end
    end

    config.vm.define "web01" do |web01|
        web01.vm.box = "geerlingguy/centos7"
        web01.vm.network "private_network", ip: "192.168.10.13"
        web01.vm.hostname = "web01"
        web01.vm.provider "virtualbox" do |vb|
            vb.name = "web01"
        end
    end
    
    config.vm.define "web02" do |web02|
        web02.vm.box = "geerlingguy/centos7"
        web02.vm.network "private_network", ip: "192.168.10.14"
        web02.vm.hostname = "web02"
        web02.vm.provider "virtualbox" do |vb|
            vb.name = "web02"
        end
    end

    config.vm.define "web03" do |web03|
        web03.vm.box = "geerlingguy/centos7"
        web03.vm.network "private_network", ip: "192.168.10.15"
        web03.vm.hostname = "db01"
        web03.vm.provider "virtualbox" do |vb|
            vb.name = "web03"
        end
    end
end