Vagrant.configure("2") do |config|
  # Web01 VM (Ubuntu 20.04)
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/bionic64"
    web01.vm.network "private_network",ip: "192.168.33.11"
    web01.vm.hostname = "web01"
  end

  # Web02 VM (Ubuntu 20.04)
  config.vm.define "web02" do |web02|
    web02.vm.box = "ubuntu/bionic64"
    web02.vm.network "private_network", ip: "192.168.33.13"
    web02.vm.hostname = "web02"
  end

  # DB01 VM (CentOS 7)
  config.vm.define "db01" do |db01|
    db01.vm.box = "centos/7"
    db01.vm.network "private_network", ip: "192.168.33.14"
    db01.vm.hostname = "db01"

    db01.vm.provision "shell", inline: <<-SHELL
      # Update and install necessary packages
      yum -y update
      yum -y install epel-release
      yum -y install mariadb-server

      # Start and enable MariaDB service
      systemctl start mariadb
      systemctl enable mariadb
    SHELL
  end
end